export const styles = {
  container: {
    position: 'relative',
    maxWidth: '1200px',
    margin: '0 auto',
    padding: '0 24px',
    fontFamily: "'Inter', sans-serif",
  },
  bgOrbTop: {
    position: "absolute",
    width: "800px",
    height: "800px",
    borderRadius: "50%",
    background: "radial-gradient(circle, rgba(99,102,241,0.08) 0%, transparent 60%)",
    top: "-200px",
    right: "-300px",
    pointerEvents: "none",
    zIndex: 0,
  },
  bgOrbBottom: {
    position: "absolute",
    width: "800px",
    height: "800px",
    borderRadius: "50%",
    background: "radial-gradient(circle, rgba(139,92,246,0.08) 0%, transparent 60%)",
    bottom: "10%",
    left: "-400px",
    pointerEvents: "none",
    zIndex: 0,
  },
  sectionLarge: {
    padding: "120px 0 80px 0",
    position: 'relative',
    zIndex: 1,
  },
  sectionStandard: {
    padding: "80px 0",
    position: 'relative',
    zIndex: 1,
  },
  sectionTitle: {
    fontSize: "clamp(32px, 4vw, 48px)",
    fontWeight: 800,
    color: "var(--text-primary)",
    margin: "0 0 12px 0",
    letterSpacing: "-0.02em",
  },
  sectionSub: {
    fontSize: "17px",
    color: "var(--text-secondary)",
    maxWidth: "600px",
    margin: "0 auto",
    lineHeight: 1.6,
  },
  heroGrid: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: "64px",
    alignItems: "center",
  },
  heroContent: {
    display: "flex",
    flexDirection: "column",
    gap: "24px",
  },
  headline: {
    fontSize: "clamp(42px, 5vw, 64px)",
    fontWeight: 800,
    lineHeight: 1.1,
    letterSpacing: "-0.02em",
    color: "var(--text-primary)",
    margin: 0,
  },
  gradientText: {
    background: "linear-gradient(135deg, #818cf8 0%, #c084fc 100%)",
    WebkitBackgroundClip: "text",
    WebkitTextFillColor: "transparent",
    backgroundClip: "text",
  },
  subheadline: {
    fontSize: "18px",
    lineHeight: 1.6,
    color: "var(--text-secondary)",
    margin: 0,
    maxWidth: "500px",
  },
  actionRow: {
    display: "flex",
    gap: "16px",
    marginTop: "16px",
  },
  heroVisual: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  stepsGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(250px, 1fr))",
    gap: "32px",
  },
  stepCard: {
    background: "rgba(19,19,43,0.6)",
    border: "1px solid rgba(255,255,255,0.06)",
    borderRadius: "16px",
    padding: "32px 24px",
    transition: "all 0.3s ease",
  },
  stepNum: {
    fontSize: "14px",
    fontWeight: 800,
    color: "#818cf8",
    marginBottom: "16px",
    fontFamily: "monospace",
    letterSpacing: "0.1em",
  },
  stepTitle: {
    fontSize: "20px",
    fontWeight: 700,
    color: "var(--text-primary)",
    margin: "0 0 12px 0",
  },
  stepDesc: {
    fontSize: "14px",
    color: "var(--text-secondary)",
    lineHeight: 1.6,
    margin: 0,
  },
  comparisonWrapper: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: "24px",
    maxWidth: "900px",
    margin: "0 auto",
  },
  compCol: {
    padding: "40px 32px",
    borderRadius: "20px",
    transition: "transform 0.3s ease",
  },
  compBadge: {
    display: "inline-block",
    background: "linear-gradient(135deg, #6366f1, #8b5cf6)",
    color: "white",
    padding: "4px 12px",
    borderRadius: "999px",
    fontSize: "11px",
    fontWeight: 800,
    letterSpacing: "0.08em",
    marginBottom: "12px",
  },
  compHeader: {
    fontSize: "22px",
    fontWeight: 700,
    marginBottom: "24px",
  },
  compList: {
    listStyle: "none",
    padding: 0,
    margin: 0,
    display: "flex",
    flexDirection: "column",
    gap: "16px",
  },
  compItem: {
    fontSize: "14px",
    color: "var(--text-secondary)",
    display: "flex",
    alignItems: "flex-start",
    gap: "12px",
    lineHeight: 1.5,
  },
  pricingGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(280px, 1fr))",
    gap: "32px",
    maxWidth: "1000px",
    margin: "0 auto",
  },
};

export const faqStyles = {
  list: {
    maxWidth: "800px",
    margin: "0 auto",
    display: "flex",
    flexDirection: "column",
    gap: "16px",
  },
  item: {
    borderRadius: "12px",
    padding: "20px 24px",
    transition: "all 0.25s ease",
  },
  trigger: {
    width: "100%",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    background: "none",
    border: "none",
    cursor: "pointer",
    padding: 0,
    textAlign: "left",
  },
  question: {
    fontSize: "16px",
    fontWeight: 600,
    color: "var(--text-primary)",
    fontFamily: "'Inter', sans-serif",
  },
  chevron: {
    fontSize: "20px",
    color: "#818cf8",
    transition: "transform 0.35s cubic-bezier(0.4,0,0.2,1)",
    flexShrink: 0,
  },
  answer: {
    fontSize: "14px",
    lineHeight: 1.7,
    color: "var(--text-secondary)",
    margin: "16px 0 0 0",
    fontFamily: "'Inter', sans-serif",
  },
};
